apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goproxify.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goproxify.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token: {{ required "global.authToken est requis" .Values.global.authToken | quote }}
  {{- if .Values.admin.config.jwtSecret }}
  jwt-secret: {{ .Values.admin.config.jwtSecret | quote }}
  {{- end }}
